import React, { useState } from "react";
import axios from "axios";

export default function CreateTracker() {
  const [name, setName] = useState("");
  const [trackerURL, setTrackerURL] = useState("");

  const handleSubmit = async () => {
    const res = await axios.post("http://localhost:5000/api/trackers", {
      userId: "6659a8123b0f42a21c94e1c8",
      name,
    });
    setTrackerURL(res.data.url);
  };

  return (
    <div className="p-6 max-w-4xl mx-auto space-y-4">
      <h2 className="text-3xl font-bold m-12">Create Invisible Image Logger</h2>
      <p className="text-lg text-gray-700">
        An invisible IP logger otherwise known as a tracking pixel is a 1x1
        pixel image that is embedded in your website and activates whenever a
        user accesses the site. This tool is valuable for monitoring user
        activities and conversion rates. Advertisers can harness the data
        gathered through the tracking pixel for various digital marketing
        strategies, such as web analysis or email marketing.
      </p>

      <input
        type="text"
        placeholder="Tracker Name"
        value={name}
        onChange={(e) => setName(e.target.value)}
        className="w-full border px-3 py-2 rounded"
      />
      <button
        onClick={handleSubmit}
        className="bg-blue-600 text-white px-4 py-2 rounded"
      >
        Generate
      </button>

      {trackerURL && (
        <div className="mt-4">
          <p className="font-medium">Embed this in your HTML:</p>
          <code className="bg-gray-100 p-2 block rounded mt-1">{`<img src="${trackerURL}" style="display:none;" />`}</code>
        </div>
      )}
        <h2 className="text-2xl font-bold mt-8">How do i use it?</h2>
      <p className="text-lg text-gray-700">
        There are many ways these can be used. The links may be inserted into
        your message, webpage or blog for statistics collection, getting the IP
        addresses of all the users who opened your message, page, blog and so
        on. An example of using this invisible image logger in HTML:{" "}
        <img src="https://grabify.link/YOUR_CODE" />
        An example of using this invisible image logger in MyBB:
        [img]https://grabify.link/YOUR_CODE[/img] Just replace
        "https://grabify.link/YOUR_CODE" with your custom link that will be
        generated by clicking the button above.
      </p>
      <h2 className="text-2xl font-bold mt-8">How Does it work?</h2>
      <p className="text-lg text-gray-700">
        The site manager or the individual dispatching an email/message
        integrates the tracking pixel by embedding a code into the HTML code of
        the website or email, as shown above. This particular code includes a
        hidden, external link to Grabify. When a visitor accesses the targeted
        website, their browser processes the HTML code. The browser then follows
        the embedded link and activates the concealed image. This action is
        recorded and documented on the tracking page. In addition, various
        information about the user is also transmitted using this method. You
        can view all the information it can log here.
      </p>
      <p className="text-lg text-gray-700">
        The server can then analyze this data to track user activity, such as
        page views, unique visitors, and geographic location.
      </p>
    </div>
  );
}
